<a target="_blank" href="https://colab.research.google.com/github/phitter-hub/phitter-kernel/blob/main/examples/fit_continuous_winequality.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **TUTORIAL: PH DISTRIBUTION ANALYSIS IN RED WINES**

In [1]:
import os
import sys

import pandas

In [2]:
if os.getenv("COLAB_RELEASE_TAG"):
   !pip install phitter --quiet
else:
   sys.path.append("../../")

In [3]:
import phitter

**Load Dataset and get PH column**

In [4]:
df = pandas.read_csv("https://raw.githubusercontent.com/aniruddhachoudhury/Red-Wine-Quality/master/winequality-red.csv")
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [5]:
data = df["pH"].to_numpy()

**Initialize the PHITTER model with the pH data, and fit the model using 2 workers for better performance**

In [6]:
phi = phitter.Phitter(data=data)
phi.fit(n_workers=2)

**Get best distribution**

In [7]:
phi.best_distribution

{'id': 'loglogistic_3p',
 'parameters': {'loc': -6.258996388634143,
  'alpha': 9.568930652898823,
  'beta': 112.46023271138603}}

**Get top 10 distrbutions sorted by sse**

In [8]:
phi.df_sorted_distributions.head(10)

            distribution passed          aic          bic  \

0         loglogistic_3p      ✅ -1452.861222 -1436.729821
1   generalized_logistic      ✅ -1452.831698 -1436.700296
2  non_central_t_student      ✅ -1455.348640 -1433.840105
3                burr_4p      ✅ -1452.855689 -1431.347154
4               logistic      ✅ -1453.060845 -1442.306578
5           t_student_3p      ✅ -1454.929535 -1438.798133
6     generalized_normal      ✅ -1451.914720 -1435.783319
7             johnson_su      ✅ -1454.379730 -1432.871195
8       inverse_gamma_3p      ✅ -1433.524429 -1417.393028
9              lognormal      ✅ -1440.998918 -1430.244650

                                          parameters     chi_square  \
                                                     test_statistic
0             loc: -6.259, alpha: 9.569, beta: 112.5      19.019373
1               c: 1.053, loc: 3.304, scale: 0.08669      19.189520
2  lambda: 0.6022, n: 11.99, loc: 3.221, scale: 0...      16.618176
3        A: 3.412, B: 38.54, C: 1.075, loc: -0.09412      16.582185
4                          mu: 3.311, sigma: 0.08512      20.930885
5                df: 11.14, loc: 3.31, scale: 0.1398      20.512066
6               beta: 1.603, mu: 3.31, alpha: 0.1894      26.330188
7  xi: 3.296, lambda: 0.3598, gamma: -0.096, delt...      18.410704
8             alpha: 229.9, loc: 0.9629, beta: 537.3      45.159276
9                           mu: 1.196, sigma: 0.0466      50.185088

                                    kolmogorov_smirnov                 \
  critical_value   p_value rejected     test_statistic critical_value
0      19.675138  0.060747    False           0.032622       0.033857
1      19.675138  0.057775    False           0.032277       0.033857
2      18.307038  0.083251    False           0.023423       0.033857
3      18.307038  0.084136    False           0.027425       0.033857
4      21.026070  0.051402    False           0.034236       0.033857
5      19.675138  0.038793     True           0.023772       0.033857
6      19.675138  0.005794     True           0.026967       0.033857
7      18.307038  0.048418     True           0.024777       0.033857
8      19.675138  0.000005     True           0.032785       0.033857
9      21.026070  0.000001     True           0.036372       0.033857

                     anderson_darling
    p_value rejected   test_statistic critical_value   p_value rejected
0  0.065077    False         1.048760        2.49236  0.332661    False
1  0.069918    False         1.021131        2.49236  0.346368    False
2  0.338928    False         0.773259        2.49236  0.500709    False
3  0.177066    False         0.815874        2.49236  0.469711    False
4  0.046026     True         1.150204        2.49236  0.287262    False
5  0.321729    False         0.765723        2.49236  0.506403    False
6  0.191772    False         0.829014        2.49236  0.460555    False
7  0.275478    False         0.743740        2.49236  0.523379    False
8  0.062888    False         2.350473        2.49236  0.059414    False
9  0.028369     True         1.678040        2.49236  0.139150    False

**Get not rejected distributions**

In [9]:
phi.df_not_rejected_distributions

             distribution          aic          bic  \

0          loglogistic_3p -1452.861222 -1436.729821
1    generalized_logistic -1452.831698 -1436.700296
2   non_central_t_student -1455.348640 -1433.840105
3                 burr_4p -1452.855689 -1431.347154
4                logistic -1453.060845 -1442.306578
5            t_student_3p -1454.929535 -1438.798133
6      generalized_normal -1451.914720 -1435.783319
7              johnson_su -1454.379730 -1432.871195
8        inverse_gamma_3p -1433.524429 -1417.393028
9               lognormal -1440.998918 -1430.244650
10       inverse_gaussian -1440.806736 -1430.052469
11                  gamma -1440.095530 -1429.341262
12                 erlang -1440.092729 -1429.338461
13               nakagami -1437.587259 -1426.832992
14                   rice -1434.055285 -1423.301018
15                 normal -1434.046163 -1423.291896
16          folded_normal -1434.046163 -1423.291896
17           fatigue_life -1438.827566 -1422.696165
18                  alpha -1438.146089 -1422.014688
19    inverse_gaussian_3p -1437.392284 -1421.260883
20               gamma_3p -1436.803167 -1420.671766
21              erlang_3p -1434.715228 -1418.583827
22             johnson_sb -1430.030437 -1408.521903

                                           parameters     chi_square  \
                                                      test_statistic
0              loc: -6.259, alpha: 9.569, beta: 112.5      19.019373
1                c: 1.053, loc: 3.304, scale: 0.08669      19.189520
2   lambda: 0.6022, n: 11.99, loc: 3.221, scale: 0...      16.618176
3         A: 3.412, B: 38.54, C: 1.075, loc: -0.09412      16.582185
4                           mu: 3.311, sigma: 0.08512      20.930885
5                 df: 11.14, loc: 3.31, scale: 0.1398      20.512066
6                beta: 1.603, mu: 3.31, alpha: 0.1894      26.330188
7   xi: 3.296, lambda: 0.3598, gamma: -0.096, delt...      18.410704
8              alpha: 229.9, loc: 0.9629, beta: 537.3      45.159276
9                            mu: 1.196, sigma: 0.0466      50.185088
10                            mu: 3.311, lambda: 1523      50.630645
11                         alpha: 460, beta: 0.007199      61.272304
12                             k: 460, beta: 0.007199      61.073752
13                             m: 114.4, omega: 10.99      78.401660
14                            v: 3.308, sigma: 0.1545     112.734197
15                           mu: 3.311, sigma: 0.1544     112.819775
16                           mu: 3.311, sigma: 0.1544     112.819775
17          gamma: 0.04422, loc: -0.176, scale: 3.484      52.177922
18            alpha: 29.64, loc: -1.262, scale: 135.4      42.975533
19              mu: 2.391, lambda: 573.7, loc: 0.9198      46.033622
20            alpha: 106.6, loc: 1.717, beta: 0.01495      47.017129
21                  k: 107, beta: 0.01495, loc: 1.717      47.914563
22  xi: -2.341e+07, lambda: 3.274e+07, gamma: -3.9...     110.090069

                                         kolmogorov_smirnov                 \
   critical_value       p_value rejected     test_statistic critical_value
0       19.675138  6.074665e-02    False           0.032622       0.033857
1       19.675138  5.777524e-02    False           0.032277       0.033857
2       18.307038  8.325139e-02    False           0.023423       0.033857
3       18.307038  8.413568e-02    False           0.027425       0.033857
4       21.026070  5.140174e-02    False           0.034236       0.033857
5       19.675138  3.879323e-02     True           0.023772       0.033857
6       19.675138  5.794074e-03     True           0.026967       0.033857
7       18.307038  4.841841e-02     True           0.024777       0.033857
8       19.675138  4.549001e-06     True           0.032785       0.033857
9       21.026070  1.296298e-06     True           0.036372       0.033857
10      21.026070  1.082169e-06     True           0.036420       0.033857
11      21.026070  1.322009e-08     True           0.037735       0.033857
12      21.026070  1.437323e-08     True           0.038164       0.033857
13      21.026070  8.319678e-12     True           0.039697       0.033857
14      21.026070  0.000000e+00     True           0.040365       0.033857
15      21.026070  0.000000e+00     True           0.040368       0.033857
16      21.026070  0.000000e+00     True           0.040368       0.033857
17      19.675138  2.531363e-07     True           0.036416       0.033857
18      19.675138  1.096794e-05     True           0.035692       0.033857
19      19.675138  3.189423e-06     True           0.034909       0.033857
20      19.675138  2.135499e-06     True           0.035038       0.033857
21      19.675138  1.478628e-06     True           0.046113       0.033857
22      18.307038  0.000000e+00     True           0.040751       0.033857

                      anderson_darling
     p_value rejected   test_statistic critical_value   p_value rejected
0   0.065077    False         1.048760        2.49236  0.332661    False
1   0.069918    False         1.021131        2.49236  0.346368    False
2   0.338928    False         0.773259        2.49236  0.500709    False
3   0.177066    False         0.815874        2.49236  0.469711    False
4   0.046026     True         1.150204        2.49236  0.287262    False
5   0.321729    False         0.765723        2.49236  0.506403    False
6   0.191772    False         0.829014        2.49236  0.460555    False
7   0.275478    False         0.743740        2.49236  0.523379    False
8   0.062888    False         2.350473        2.49236  0.059414    False
9   0.028369     True         1.678040        2.49236  0.139150    False
10  0.028050     True         1.685093        2.49236  0.137863    False
11  0.020514     True         1.675565        2.49236  0.139604    False
12  0.018479     True         1.680664        2.49236  0.138670    False
13  0.012600     True         1.840408        2.49236  0.112621    False
14  0.010615     True         1.863786        2.49236  0.109283    False
15  0.010605     True         1.864112        2.49236  0.109237    False
16  0.010605     True         1.864112        2.49236  0.109237    False
17  0.028076     True         1.651334        2.49236  0.144141    False
18  0.033201     True         1.831517        2.49236  0.113920    False
19  0.039639     True         1.794774        2.49236  0.119465    False
20  0.038512     True         1.816206        2.49236  0.116196    False
21  0.002155     True         2.460070        2.49236  0.051993    False
22  0.009599     True         1.921393        2.49236  0.101506    False

**Get parameters by `id_distribution`**

In [10]:
phi.get_parameters("weibull")

{'alpha': 26.8035318858474, 'beta': 3.3793892270902433}

**Get sum squared error by `id_distribution`**

In [11]:
phi.get_sse("weibull")

1.345573862824171

**Get results chi square test by `id_distribution`**

In [12]:
phi.get_test_chi_square("weibull")

{'test_statistic': None,
 'critical_value': None,
 'p_value': None,
 'rejected': None}

**Plot a histogram to visualize the distribution**

In [13]:
phi.plot_histogram()

**Plot histogram and compare with N distributions**

In [14]:
phi.plot_histogram_distributions()

**Plot the histogram along with the `id_distribution` distribution curve for comparison**

In [15]:
phi.plot_distribution("normal")

**Generate an empirical cumulative distribution function (ECDF) plot for the data**

In [16]:
phi.plot_ecdf()

**Plot the ECDF to visualize how closely the dataset values follow a `id_distribution`**

In [17]:
phi.plot_ecdf_distribution("normal")

**Create a QQ plot for the `id_distribution` to check the quantiles against a `id_distribution`**

In [18]:
phi.qq_plot("normal")

**Generate a QQ plot with a regression line for the `id_distribution` to assess normality through quantile comparisons**

In [19]:
phi.qq_plot_regression("normal")