In [1]:
import sys

In [2]:
sys.path.append("../../../")
import phitter

In [3]:
def get_data(path: str) -> list[float | int]:
    sample_distribution_file = open(path, "r")
    data = [float(x.replace(",", ".")) for x in sample_distribution_file.read().splitlines()]
    sample_distribution_file.close()
    return data

In [4]:
path = "../../../distributions_samples/continuous_distributions_sample/sample_beta.txt"
data = get_data(path)

In [5]:
phi = phitter.Phitter(data=data)
phi.fit(n_workers=1)

In [6]:
phi.best_distribution

{'id': 'generalized_gamma',
 'parameters': {'a': np.float64(805.3155403562906),
  'd': np.float64(86.99775470906536),
  'p': np.float64(16.75970080463159)}}

In [7]:
phi.sorted_distributions

{'generalized_gamma': {'chi_square': {'test_statistic': np.float64(14.699283827631858),
   'critical_value': np.float64(22.362032494826934),
   'p_value': np.float64(0.32650010173511446),
   'rejected': np.False_},
  'kolmogorov_smirnov': {'test_statistic': np.float64(0.011638481323863081),
   'critical_value': np.float64(0.02915677208094496),
   'p_value': np.float64(0.9285320027912259),
   'rejected': np.False_},
  'anderson_darling': {'test_statistic': np.float64(0.20851897067404934),
   'critical_value': np.float64(2.4923268305268924),
   'p_value': np.float64(0.9879089706990839),
   'rejected': np.False_},
  'aic': 4321.730382171181,
  'bic': np.float64(4338.761193608635),
  'sse': np.float64(5.44432712390386),
  'parameters': {'a': np.float64(805.3155403562906),
   'd': np.float64(86.99775470906536),
   'p': np.float64(16.75970080463159)},
  'n_test_passed': 3,
  'n_test_null': 0},
 'loggamma': {'chi_square': {'test_statistic': np.float64(14.701357421346438),
   'critical_value': np.float64(22.362032494826934),
   'p_value': np.float64(0.326365524186357),
   'rejected': np.False_},
  'kolmogorov_smirnov': {'test_statistic': np.float64(0.011717515199630213),
   'critical_value': np.float64(0.02915677208094496),
   'p_value': np.float64(0.9249481125842145),
   'rejected': np.False_},
  'anderson_darling': {'test_statistic': np.float64(0.2119159173380467),
   'critical_value': np.float64(2.4923268305268924),
   'p_value': np.float64(0.9868080417003893),
   'rejected': np.False_},
  'aic': 19823.770294642767,
  'bic': np.float64(19840.80110608022),
  'sse': np.float64(2.002565446911337e-06),
  'parameters': {'c': np.float64(7.7906855219975215),
   'mu': np.float64(753.8625547143147),
   'sigma': np.float64(65.25437287614032)},
  'n_test_passed': 3,
  'n_test_null': 0},
 'weibull_3p': {'chi_square': {'test_statistic': np.float64(19.50613582857832),
   'critical_value': np.float64(22.362032494826934),
   'p_value': np.float64(0.10822732913122812),
   'rejected': np.False_},
  'kolmogorov_smirnov': {'test_statistic': np.float64(0.009407842957641632),
   'critical_value': np.float64(0.02915677208094496),
   'p_value': np.float64(0.9901254125553746),
   'rejected': np.False_},
  'anderson_darling': {'test_statistic': np.float64(0.29860389985151414),
   'critical_value': np.float64(2.4923268305268924),
   'p_value': np.float64(0.9391981995286119),
   'rejected': np.False_},
  'aic': 19827.109093331717,
  'bic': np.float64(19844.13990476917),
  'sse': np.float64(2.1120082501326804e-06),
  'parameters': {'alpha': np.float64(5.963385914534697),
   'loc': np.float64(759.6272393966783),
   'beta': np.float64(133.62071167922645)},
  'n_test_passed': 3,
  'n_test_null': 0},
 'johnson_sb': {'chi_square': {'test_statistic': np.float64(15.51243131262429),
   'critical_value': np.float64(21.02606981748307),
   'p_value': np.float64(0.21460140992906707),
   'rejected': np.False_},
  'kolmogorov_smirnov': {'test_statistic': np.float64(0.011890836993289633),
   'critical_value': np.float64(0.02915677208094496),
   'p_value': np.float64(0.9167538887417859),
   'rejected': np.False_},
  'anderson_darling': {'test_statistic': np.float64(0.23283036612247088),
   'critical_value': np.float64(2.4923268305268924),
   'p_value': np.float64(0.9787188080165576),
   'rejected': np.False_},
  'aic': 19826.106561939083,
  'bic': np.float64(19848.814310522353),
  'sse': np.float64(2.005554104701933e-06),
  'parameters': {'xi': np.float64(-161.32891731800058),
   'lambda': np.float64(1213.5774041868667),
   'gamma': np.float64(-11.039815662319977),
   'delta': np.float64(6.020654944380659)},
  'n_test_passed': 3,
  'n_test_null': 0},
 'non_central_t_student': {'chi_square': {'test_statistic': np.float64(14.892833917648082),
   'critical_value': np.float64(21.02606981748307),
   'p_value': np.float64(0.24734947217500347),
   'rejected': np.False_},
  'kolmogorov_smirnov': {'test_statistic': np.float64(0.014306695135527847),
   'critical_value': np.float64(0.02915677208094496),
   'p_value': np.float64(0.7633828176973931),
   'rejected': np.False_},
  'anderson_darling': {'test_statistic': np.float64(0.34046823096605294),
   'critical_value': np.float64(2.4923268305268924),
   'p_value': np.float64(0.9049521461453793),
   'rejected': np.False_},
  'aic': 19826.646604599417,
  'bic': np.float64(19849.354353182687),
  'sse': np.float64(2.360890044189441e-06),
  'parameters': {'lambda': np.float64(-11.12433544321511),
   'n': np.float64(70.790692022514),
   'loc': np.float64(1077.9237897863886),
   'scale': np.float64(17.287164950693427)},
  'n_test_passed': 3,
  'n_test_null': 0},
 'johnson_su': {'chi_square': {'test_statistic': np.float64(20.14814198059029),
   'critical_value': np.float64(21.02606981748307),
   'p_value': np.float64(0.06433499733719239),
   'rejected': np.False_},
  'kolmogorov_smirnov': {'test_statistic': np.float64(0.011702194231956842),
   'critical_value': np.float64(0.02915677208094496),
   'p_value': np.float64(0.9256503884727609),
   'rejected': np.False_},
  'anderson_darling': {'test_statistic': np.float64(0.30464867946557206),
   'critical_value': np.float64(2.4923268305268924),
   'p_value': np.float64(0.934620463180324),
   'rejected': np.False_},
  'aic': 19829.8068796379,
  'bic': np.float64(19852.51462822117),
  'sse': np.float64(2.1552270776039404e-06),
  'parameters': {'xi': np.float64(1028.6008917406054),
   'lambda': np.float64(39.19044903123062),
   'gamma': np.float64(12.564545656178632),
   'delta': np.float64(6.261301589405481)},
  'n_test_passed': 3,
  'n_test_null': 0},
 'burr': {'chi_square': {'test_statistic': np.float64(21.655527624854372),
   'critical_value': np.float64(22.362032494826934),
   'p_value': np.float64(0.060934396276894676),
   'rejected': np.False_},
  'kolmogorov_smirnov': {'test_statistic': np.float64(0.025207047648464487),
   'critical_value': np.float64(0.02915677208094496),
   'p_value': np.float64(0.12664292490139972),
   'rejected': np.False_},
  'anderson_darling': {'test_statistic': np.float64(1.8574825839828009),
   'critical_value': np.float64(2.4923268305268924),
   'p_value': np.float64(0.11017027175229788),
   'rejected': np.False_},
  'aic': 19840.645428743832,
  'bic': np.float64(19857.676240181285),
  'sse': np.float64(5.4389524257548525e-06),
  'parameters': {'A': np.float64(904.4523694683762),
   'B': np.float64(51.636740559663416),
   'C': np.float64(2.5063959520766357)},
  'n_test_passed': 3,
  'n_test_null': 0},
 'burr_4p': {'chi_square': {'test_statistic': np.float64(19.37192340136254),
   'critical_value': np.float64(21.02606981748307),
   'p_value': np.float64(0.079939481370359),
   'rejected': np.False_},
  'kolmogorov_smirnov': {'test_statistic': np.float64(0.018165762511881733),
   'critical_value': np.float64(0.02915677208094496),
   'p_value': np.float64(0.4692154128940059),
   'rejected': np.False_},
  'anderson_darling': {'test_statistic': np.float64(0.7126759486468472),
   'critical_value': np.float64(2.4923268305268924),
   'p_value': np.float64(0.5483203376842196),
   'rejected': np.False_},
  'aic': 19839.767214987238,
  'bic': np.float64(19862.47496357051),
  'sse': np.float64(4.978267402573367e-06),
  'parameters': {'A': np.float64(904.4523694683762),
   'B': np.float64(51.636740559663416),
   'C': np.float64(2.5063959520766357),
   'loc': np.float64(0.8460973115800341)},
  'n_test_passed': 3,
  'n_test_null': 0},
 'kumaraswamy': {'chi_square': {'test_statistic': np.float64(28.256278368815405),
   'critical_value': np.float64(21.02606981748307),
   'p_value': np.float64(0.005073671640993926),
   'rejected': np.True_},
  'kolmogorov_smirnov': {'test_statistic': np.float64(0.012157668413438794),
   'critical_value': np.float64(0.02915677208094496),
   'p_value': np.float64(0.9032618136671798),
   'rejected': np.False_},
  'anderson_darling': {'test_statistic': np.float64(0.49870451468677857),
   'critical_value': np.float64(2.4923268305268924),
   'p_value': np.float64(0.7481211606488822),
   'rejected': np.False_},
  'aic': 19834.733154911184,
  'bic': np.float64(19857.440903494455),
  'sse': np.float64(2.747328700286749e-06),
  'parameters': {'alpha': np.float64(6.80107701346655),
   'beta': np.float64(137.97784453905385),
   'min': np.float64(743.2415228907947),
   'max': np.float64(1053.419104283398)},
  'n_test_passed': 2,
  'n_test_null': 0},
 'beta': {'chi_square': {'test_statistic': np.float64(27.57659041908278),
   'critical_value': np.float64(21.02606981748307),
   'p_value': np.float64(0.006377072851541987),
   'rejected': np.True_},
  'kolmogorov_smirnov': {'test_statistic': np.float64(0.010233296920341028),
   'critical_value': np.float64(0.02915677208094496),
   'p_value': np.float64(0.9758613934440539),
   'rejected': np.False_},
  'anderson_darling': {'test_statistic': np.float64(0.36426366739488003),
   'critical_value': np.float64(2.4923268305268924),
   'p_value': np.float64(0.8832847743621575),
   'rejected': np.False_},
  'aic': 19835.98927824226,
  'bic': np.float64(19858.69702682553),
  'sse': np.float64(2.2981606559500745e-06),
  'parameters': {'alpha': np.float64(45.83246778284843),
   'beta': np.float64(10.337834518530881),
   'A': np.float64(499.0939442805805),
   'B': np.float64(970.2639535360801)},
  'n_test_passed': 2,
  'n_test_null': 0},
 'dagum_4p': {'chi_square': {'test_statistic': np.float64(34.2029760606009),
   'critical_value': np.float64(21.02606981748307),
   'p_value': np.float64(0.0006265685281567901),
   'rejected': np.True_},
  'kolmogorov_smirnov': {'test_statistic': np.float64(0.024180808390558917),
   'critical_value': np.float64(0.02915677208094496),
   'p_value': np.float64(0.15768632314869158),
   'rejected': np.False_},
  'anderson_darling': {'test_statistic': np.float64(2.226239638698189),
   'critical_value': np.float64(2.4923268305268924),
   'p_value': np.float64(0.06921896193386101),
   'rejected': np.False_},
  'aic': 19850.32758478143,
  'bic': np.float64(19873.0353333647),
  'sse': np.float64(1.1557906414817067e-05),
  'parameters': {'a': np.float64(73.80896034958256),
   'b': np.float64(896.2435914160488),
   'p': np.float64(0.7126797543833516),
   'loc': np.float64(-5.087454845730419)},
  'n_test_passed': 2,
  'n_test_null': 0},
 'mcdonald': {'chi_square': {'test_statistic': np.float64(44.59112265547088),
   'critical_value': np.float64(19.67513757268249),
   'p_value': np.float64(5.724890346447964e-06),
   'rejected': np.True_},
  'kolmogorov_smirnov': {'test_statistic': np.float64(0.013048660166198767),
   'critical_value': np.float64(0.02915677208094496),
   'p_value': np.float64(0.8511755883483547),
   'rejected': np.False_},
  'anderson_darling': {'test_statistic': np.float64(0.6033258966044741),
   'critical_value': np.float64(2.4923268305268924),
   'p_value': np.float64(0.6448424071872134),
   'rejected': np.False_},
  'aic': 19849.643585592297,
  'bic': np.float64(19878.02827132139),
  'sse': np.float64(2.8617908785543238e-06),
  'parameters': {'a': np.float64(3.9328335016183975),
   'b': np.float64(9.02159903283252),
   'c': np.float64(4.476005632248741),
   'min': np.float64(638.2258901219277),
   'max': np.float64(963.5271823770134)},
  'n_test_passed': 2,
  'n_test_null': 0},
 'exponentiated_kumaraswamy': {'chi_square': {'test_statistic': np.float64(56.825252808944406),
   'critical_value': np.float64(19.67513757268249),
   'p_value': np.float64(3.583181940047808e-08),
   'rejected': np.True_},
  'kolmogorov_smirnov': {'test_statistic': np.float64(0.012750515738244372),
   'critical_value': np.float64(0.02915677208094496),
   'p_value': np.float64(0.8697237674954928),
   'rejected': np.False_},
  'anderson_darling': {'test_statistic': np.float64(0.6388918841721534),
   'critical_value': np.float64(2.4923268305268924),
   'p_value': np.float64(0.6119914974165406),
   'rejected': np.False_},
  'aic': 19861.328562231913,
  'bic': np.float64(19889.713247961005),
  'sse': np.float64(2.8837077797743062e-06),
  'parameters': {'alpha': np.float64(6.515706133219352),
   'beta': np.float64(6.168209535380089),
   'lambda': np.float64(2.775199991203011),
   'min': np.float64(619.6455405936982),
   'max': np.float64(955.7862694254383)},
  'n_test_passed': 2,
  'n_test_null': 0},
 'half_normal': {'chi_square': {'test_statistic': np.float64(1967.1726596816286),
   'critical_value': np.float64(23.684791304840576),
   'p_value': np.float64(0.0),
   'rejected': np.True_},
  'kolmogorov_smirnov': {'test_statistic': np.float64(0.9173802353596332),
   'critical_value': np.float64(0.02915677208094496),
   'p_value': np.float64(0.0),
   'rejected': np.True_},
  'anderson_darling': {'test_statistic': None,
   'critical_value': None,
   'p_value': None,
   'rejected': None},
  'aic': 19063.778808730003,
  'bic': np.float64(19075.13268302164),
  'sse': np.float64(0.0013146655976853927),
  'parameters': {'mu': np.float64(851.5848052687289),
   'sigma': np.float64(40.0595715351334)},
  'n_test_passed': 0,
  'n_test_null': 1},
 'normal': {'chi_square': {'test_statistic': np.float64(60.51643239531984),
   'critical_value': np.float64(23.684791304840576),
   'p_value': np.float64(9.521756016983574e-08),
   'rejected': np.True_},
  'kolmogorov_smirnov': {'test_statistic': np.float64(0.035447930380450965),
   'critical_value': np.float64(0.02915677208094496),
   'p_value': np.float64(0.008610748147569125),
   'rejected': np.True_},
  'anderson_darling': {'test_statistic': np.float64(4.022972110796218),
   'critical_value': np.float64(2.4923268305268924),
   'p_value': np.float64(0.008498410517288058),
   'rejected': np.True_},
  'aic': 19870.210078147247,
  'bic': np.float64(19881.563952438883),
  'sse': np.float64(1.179790645625211e-05),
  'parameters': {'mu': np.float64(883.5477189089899),
   'sigma': np.float64(24.148321333038766)},
  'n_test_passed': 0,
  'n_test_null': 0},
 'rice': {'chi_square': {'test_statistic': np.float64(60.522961764125974),
   'critical_value': np.float64(23.684791304840576),
   'p_value': np.float64(9.496635755557037e-08),
   'rejected': np.True_},
  'kolmogorov_smirnov': {'test_statistic': np.float64(0.03544926247016156),
   'critical_value': np.float64(0.02915677208094496),
   'p_value': np.float64(0.008607229791688598),
   'rejected': np.True_},
  'anderson_darling': {'test_statistic': np.float64(4.023356725327176),
   'critical_value': np.float64(2.4923268305268924),
   'p_value': np.float64(0.00849473573170867),
   'rejected': np.True_},
  'aic': 19870.215579761832,
  'bic': np.float64(19881.569454053468),
  'sse': np.float64(1.1798885870835775e-05),
  'parameters': {'v': np.float64(883.2174101471106),
   'sigma': np.float64(24.152840676758686)},
  'n_test_passed': 0,
  'n_test_null': 0},
 'generalized_normal': {'chi_square': {'test_statistic': np.float64(52.96347396721571),
   'critical_value': np.float64(22.362032494826934),
   'p_value': np.float64(9.169967402078427e-07),
   'rejected': np.True_},
  'kolmogorov_smirnov': {'test_statistic': np.float64(0.03146924097376058),
   'critical_value': np.float64(0.02915677208094496),
   'p_value': np.float64(0.02725461616236413),
   'rejected': np.True_},
  'anderson_darling': {'test_statistic': np.float64(3.566837037175901),
   'critical_value': np.float64(2.4923268305268924),
   'p_value': np.float64(0.014239764345318817),
   'rejected': np.True_},
  'aic': 19870.46553351934,
  'bic': np.float64(19887.49634495679),
  'sse': np.float64(1.164342999047156e-05),
  'parameters': {'beta': np.float64(1.879226190935344),
   'mu': np.float64(883.7454919029467),
   'alpha': np.float64(32.99544726386294)},
  'n_test_passed': 0,
  'n_test_null': 0},
 't_student_3p': {'chi_square': {'test_statistic': np.float64(60.59535381689419),
   'critical_value': np.float64(22.362032494826934),
   'p_value': np.float64(4.110334961282547e-08),
   'rejected': np.True_},
  'kolmogorov_smirnov': {'test_statistic': np.float64(0.03543421160444482),
   'critical_value': np.float64(0.02915677208094496),
   'p_value': np.float64(0.008647058659201567),
   'rejected': np.True_},
  'anderson_darling': {'test_statistic': np.float64(4.021428407899748),
   'critical_value': np.float64(2.4923268305268924),
   'p_value': np.float64(0.008513176127999844),
   'rejected': np.True_},
  'aic': 19872.208808284162,
  'bic': np.float64(19889.239619721615),
  'sse': np.float64(1.1794798712464517e-05),
  'parameters': {'df': np.float64(214406.25776772574),
   'loc': np.float64(883.5477526862255),
   'scale': np.float64(24.142609142084765)},
  'n_test_passed': 0,
  'n_test_null': 0},
 'dagum': {'chi_square': {'test_statistic': np.float64(48.989477164836025),
   'critical_value': np.float64(22.362032494826934),
   'p_value': np.float64(4.439644491260886e-06),
   'rejected': np.True_},
  'kolmogorov_smirnov': {'test_statistic': np.float64(0.03447963378211649),
   'critical_value': np.float64(0.02915677208094496),
   'p_value': np.float64(0.011542376930023024),
   'rejected': np.True_},
  'anderson_darling': {'test_statistic': np.float64(4.600068305715467),
   'critical_value': np.float64(2.4923268305268924),
   'p_value': np.float64(0.004460416983611215),
   'rejected': np.True_},
  'aic': 19875.55329320224,
  'bic': np.float64(19892.584104639693),
  'sse': np.float64(2.2066428529362482e-05),
  'parameters': {'a': np.float64(88.11625149154641),
   'b': np.float64(895.1315409000871),
   'p': np.float64(0.5447255036123255)},
  'n_test_passed': 0,
  'n_test_null': 0},
 'generalized_logistic': {'chi_square': {'test_statistic': np.float64(50.75142764506321),
   'critical_value': np.float64(22.362032494826934),
   'p_value': np.float64(2.2144979012761468e-06),
   'rejected': np.True_},
  'kolmogorov_smirnov': {'test_statistic': np.float64(0.035414812241991445),
   'critical_value': np.float64(0.02915677208094496),
   'p_value': np.float64(0.008698641743906443),
   'rejected': np.True_},
  'anderson_darling': {'test_statistic': np.float64(4.851763241342269),
   'critical_value': np.float64(2.4923268305268924),
   'p_value': np.float64(0.003375754808245257),
   'rejected': np.True_},
  'aic': 19877.639315901426,
  'bic': np.float64(19894.67012733888),
  'sse': np.float64(2.2733040688188537e-05),
  'parameters': {'c': np.float64(0.5926516281300741),
   'loc': np.float64(893.8822785170362),
   'scale': np.float64(10.43471621373777)},
  'n_test_passed': 0,
  'n_test_null': 0},
 'gamma': {'chi_square': {'test_statistic': np.float64(80.83404072476705),
   'critical_value': np.float64(23.684791304840576),
   'p_value': np.float64(1.9810486584503906e-11),
   'rejected': np.True_},
  'kolmogorov_smirnov': {'test_statistic': np.float64(0.03897727834543263),
   'critical_value': np.float64(0.02915677208094496),
   'p_value': np.float64(0.0027631680283340954),
   'rejected': np.True_},
  'anderson_darling': {'test_statistic': np.float64(5.116282956599207),
   'critical_value': np.float64(2.4923268305268924),
   'p_value': np.float64(0.0025229461691406163),
   'rejected': np.True_},
  'aic': 19886.01451551461,
  'bic': np.float64(19897.368389806245),
  'sse': np.float64(1.4580538858282085e-05),
  'parameters': {'alpha': np.float64(1338.7088286413687),
   'beta': np.float64(0.6599999193294979)},
  'n_test_passed': 0,
  'n_test_null': 0},
 'erlang': {'chi_square': {'test_statistic': np.float64(81.7731973617431),
   'critical_value': np.float64(23.684791304840576),
   'p_value': np.float64(1.3250844865808631e-11),
   'rejected': np.True_},
  'kolmogorov_smirnov': {'test_statistic': np.float64(0.03582975292896251),
   'critical_value': np.float64(0.02915677208094496),
   'p_value': np.float64(0.007654091524526452),
   'rejected': np.True_},
  'anderson_darling': {'test_statistic': np.float64(4.651510887093536),
   'critical_value': np.float64(2.4923268305268924),
   'p_value': np.float64(0.004212995778911877),
   'rejected': np.True_},
  'aic': 19886.1546796811,
  'bic': np.float64(19897.508553972737),
  'sse': np.float64(1.3621357260361676e-05),

In [8]:
phi.summarize()

,distribution,aic,bic,parameters,chi_square,kolmogorov_smirnov,anderson_darling
0,generalized_gamma,4321.730382,4338.761194,"a: 805.3, d: 87, p: 16.76",✅,✅,✅
1,loggamma,19823.770295,19840.801106,"c: 7.791, mu: 753.9, sigma: 65.25",✅,✅,✅
2,weibull_3p,19827.109093,19844.139905,"alpha: 5.963, loc: 759.6, beta: 133.6",✅,✅,✅
3,johnson_sb,19826.106562,19848.814311,"xi: -161.3, lambda: 1214, gamma: -11.04, delta...",✅,✅,✅
4,non_central_t_student,19826.646605,19849.354353,"lambda: -11.12, n: 70.79, loc: 1078, scale: 17.29",✅,✅,✅
5,johnson_su,19829.806880,19852.514628,"xi: 1029, lambda: 39.19, gamma: 12.56, delta: ...",✅,✅,✅
6,burr,19840.645429,19857.676240,"A: 904.5, B: 51.64, C: 2.506",✅,✅,✅
7,burr_4p,19839.767215,19862.474964,"A: 904.5, B: 51.64, C: 2.506, loc: 0.8461",✅,✅,✅
8,kumaraswamy,19834.733155,19857.440903,"alpha: 6.801, beta: 138, min: 743.2, max: 1053",✖️,✅,✅
9,beta,19835.989278,19858.697027,"alpha: 45.83, beta: 10.34, A: 499.1, B: 970.3",✖️,✅,✅
10,dagum_4p,19850.327585,19873.035333,"a: 73.81, b: 896.2, p: 0.7127, loc: -5.087",✖️,✅,✅
11,mcdonald,19849.643586,19878.028271,"a: 3.933, b: 9.022, c: 4.476, min: 638.2, max:...",✖️,✅,✅
12,exponentiated_kumaraswamy,19861.328562,19889.713248,"alpha: 6.516, beta: 6.168, lambda: 2.775, min:...",✖️,✅,✅
13,half_normal,19063.778809,19075.132683,"mu: 851.6, sigma: 40.06",✖️,✖️,✖️
14,normal,19870.210078,19881.563952,"mu: 883.5, sigma: 24.15",✖️,✖️,✖️
15,rice,19870.215580,19881.569454,"v: 883.2, sigma: 24.15",✖️,✖️,✖️
16,generalized_normal,19870.465534,19887.496345,"beta: 1.879, mu: 883.7, alpha: 33",✖️,✖️,✖️
17,t_student_3p,19872.208808,19889.239620,"df: 2.144e+05, loc: 883.5, scale: 24.14",✖️,✖️,✖️
18,dagum,19875.553293,19892.584105,"a: 88.12, b: 895.1, p: 0.5447",✖️,✖️,✖️
19,generalized_logistic,19877.639316,19894.670127,"c: 0.5927, loc: 893.9, scale: 10.43",✖️,✖️,✖️

In [9]:
phi.summarize_info()

,distribution,aic,bic,parameters,chi_square,kolmogorov_smirnov,anderson_darling
0,generalized_gamma,4321.730382,4338.761194,"{'a': 805.3155403562906, 'd': 86.9977547090653...",False,False,False
1,loggamma,19823.770295,19840.801106,"{'c': 7.7906855219975215, 'mu': 753.8625547143...",False,False,False
2,weibull_3p,19827.109093,19844.139905,"{'alpha': 5.963385914534697, 'loc': 759.627239...",False,False,False
3,johnson_sb,19826.106562,19848.814311,"{'xi': -161.32891731800058, 'lambda': 1213.577...",False,False,False
4,non_central_t_student,19826.646605,19849.354353,"{'lambda': -11.12433544321511, 'n': 70.7906920...",False,False,False
5,johnson_su,19829.806880,19852.514628,"{'xi': 1028.6008917406054, 'lambda': 39.190449...",False,False,False
6,burr,19840.645429,19857.676240,"{'A': 904.4523694683762, 'B': 51.6367405596634...",False,False,False
7,burr_4p,19839.767215,19862.474964,"{'A': 904.4523694683762, 'B': 51.6367405596634...",False,False,False
8,kumaraswamy,19834.733155,19857.440903,"{'alpha': 6.80107701346655, 'beta': 137.977844...",True,False,False
9,beta,19835.989278,19858.697027,"{'alpha': 45.83246778284843, 'beta': 10.337834...",True,False,False

In [10]:
phi.df_not_rejected_distributions

                 distribution           aic           bic  \

0           generalized_gamma   4321.730382   4338.761194
1                    loggamma  19823.770295  19840.801106
2                  weibull_3p  19827.109093  19844.139905
3                  johnson_sb  19826.106562  19848.814311
4       non_central_t_student  19826.646605  19849.354353
5                  johnson_su  19829.806880  19852.514628
6                        burr  19840.645429  19857.676240
7                     burr_4p  19839.767215  19862.474964
8                 kumaraswamy  19834.733155  19857.440903
9                        beta  19835.989278  19858.697027
10                   dagum_4p  19850.327585  19873.035333
11                   mcdonald  19849.643586  19878.028271
12  exponentiated_kumaraswamy  19861.328562  19889.713248

                                           parameters     chi_square  \
                                                      test_statistic
0                           a: 805.3, d: 87, p: 16.76      14.699284
1                   c: 7.791, mu: 753.9, sigma: 65.25      14.701357
2               alpha: 5.963, loc: 759.6, beta: 133.6      19.506136
3   xi: -161.3, lambda: 1214, gamma: -11.04, delta...      15.512431
4   lambda: -11.12, n: 70.79, loc: 1078, scale: 17.29      14.892834
5   xi: 1029, lambda: 39.19, gamma: 12.56, delta: ...      20.148142
6                        A: 904.5, B: 51.64, C: 2.506      21.655528
7           A: 904.5, B: 51.64, C: 2.506, loc: 0.8461      19.371923
8      alpha: 6.801, beta: 138, min: 743.2, max: 1053      28.256278
9       alpha: 45.83, beta: 10.34, A: 499.1, B: 970.3      27.576590
10         a: 73.81, b: 896.2, p: 0.7127, loc: -5.087      34.202976
11  a: 3.933, b: 9.022, c: 4.476, min: 638.2, max:...      44.591123
12  alpha: 6.516, beta: 6.168, lambda: 2.775, min:...      56.825253

                                         kolmogorov_smirnov                 \
   critical_value       p_value rejected     test_statistic critical_value
0       22.362032  3.265001e-01    False           0.011638       0.029157
1       22.362032  3.263655e-01    False           0.011718       0.029157
2       22.362032  1.082273e-01    False           0.009408       0.029157
3       21.026070  2.146014e-01    False           0.011891       0.029157
4       21.026070  2.473495e-01    False           0.014307       0.029157
5       21.026070  6.433500e-02    False           0.011702       0.029157
6       22.362032  6.093440e-02    False           0.025207       0.029157
7       21.026070  7.993948e-02    False           0.018166       0.029157
8       21.026070  5.073672e-03     True           0.012158       0.029157
9       21.026070  6.377073e-03     True           0.010233       0.029157
10      21.026070  6.265685e-04     True           0.024181       0.029157
11      19.675138  5.724890e-06     True           0.013049       0.029157
12      19.675138  3.583182e-08     True           0.012751       0.029157

                      anderson_darling
     p_value rejected   test_statistic critical_value   p_value rejected
0   0.928532    False         0.208519       2.492327  0.987909    False
1   0.924948    False         0.211916       2.492327  0.986808    False
2   0.990125    False         0.298604       2.492327  0.939198    False
3   0.916754    False         0.232830       2.492327  0.978719    False
4   0.763383    False         0.340468       2.492327  0.904952    False
5   0.925650    False         0.304649       2.492327  0.934620    False
6   0.126643    False         1.857483       2.492327  0.110170    False
7   0.469215    False         0.712676       2.492327  0.548320    False
8   0.903262    False         0.498705       2.492327  0.748121    False
9   0.975861    False         0.364264       2.492327  0.883285    False
10  0.157686    False         2.226240       2.492327  0.069219    False
11  0.851176    False         0.603326       2.492327  0.644842    False
12  0.869724    False         0.638892       2.492327  0.611991    False

In [11]:
phi.df_sorted_distributions.head(10)

            distribution passed           aic           bic  \

0      generalized_gamma      ✅   4321.730382   4338.761194
1               loggamma      ✅  19823.770295  19840.801106
2             weibull_3p      ✅  19827.109093  19844.139905
3             johnson_sb      ✅  19826.106562  19848.814311
4  non_central_t_student      ✅  19826.646605  19849.354353
5             johnson_su      ✅  19829.806880  19852.514628
6                   burr      ✅  19840.645429  19857.676240
7                burr_4p      ✅  19839.767215  19862.474964
8            kumaraswamy      ✅  19834.733155  19857.440903
9                   beta      ✅  19835.989278  19858.697027

                                          parameters     chi_square  \
                                                     test_statistic
0                          a: 805.3, d: 87, p: 16.76      14.699284
1                  c: 7.791, mu: 753.9, sigma: 65.25      14.701357
2              alpha: 5.963, loc: 759.6, beta: 133.6      19.506136
3  xi: -161.3, lambda: 1214, gamma: -11.04, delta...      15.512431
4  lambda: -11.12, n: 70.79, loc: 1078, scale: 17.29      14.892834
5  xi: 1029, lambda: 39.19, gamma: 12.56, delta: ...      20.148142
6                       A: 904.5, B: 51.64, C: 2.506      21.655528
7          A: 904.5, B: 51.64, C: 2.506, loc: 0.8461      19.371923
8     alpha: 6.801, beta: 138, min: 743.2, max: 1053      28.256278
9      alpha: 45.83, beta: 10.34, A: 499.1, B: 970.3      27.576590

                                    kolmogorov_smirnov                 \
  critical_value   p_value rejected     test_statistic critical_value
0      22.362032  0.326500    False           0.011638       0.029157
1      22.362032  0.326366    False           0.011718       0.029157
2      22.362032  0.108227    False           0.009408       0.029157
3      21.026070  0.214601    False           0.011891       0.029157
4      21.026070  0.247349    False           0.014307       0.029157
5      21.026070  0.064335    False           0.011702       0.029157
6      22.362032  0.060934    False           0.025207       0.029157
7      21.026070  0.079939    False           0.018166       0.029157
8      21.026070  0.005074     True           0.012158       0.029157
9      21.026070  0.006377     True           0.010233       0.029157

                     anderson_darling
    p_value rejected   test_statistic critical_value   p_value rejected
0  0.928532    False         0.208519       2.492327  0.987909    False
1  0.924948    False         0.211916       2.492327  0.986808    False
2  0.990125    False         0.298604       2.492327  0.939198    False
3  0.916754    False         0.232830       2.492327  0.978719    False
4  0.763383    False         0.340468       2.492327  0.904952    False
5  0.925650    False         0.304649       2.492327  0.934620    False
6  0.126643    False         1.857483       2.492327  0.110170    False
7  0.469215    False         0.712676       2.492327  0.548320    False
8  0.903262    False         0.498705       2.492327  0.748121    False
9  0.975861    False         0.364264       2.492327  0.883285    False

In [12]:
phi.sorted_distributions

{'generalized_gamma': {'chi_square': {'test_statistic': np.float64(14.699283827631858),
   'critical_value': np.float64(22.362032494826934),
   'p_value': np.float64(0.32650010173511446),
   'rejected': np.False_},
  'kolmogorov_smirnov': {'test_statistic': np.float64(0.011638481323863081),
   'critical_value': np.float64(0.02915677208094496),
   'p_value': np.float64(0.9285320027912259),
   'rejected': np.False_},
  'anderson_darling': {'test_statistic': np.float64(0.20851897067404934),
   'critical_value': np.float64(2.4923268305268924),
   'p_value': np.float64(0.9879089706990839),
   'rejected': np.False_},
  'aic': 4321.730382171181,
  'bic': np.float64(4338.761193608635),
  'sse': np.float64(5.44432712390386),
  'parameters': {'a': np.float64(805.3155403562906),
   'd': np.float64(86.99775470906536),
   'p': np.float64(16.75970080463159)},
  'n_test_passed': 3,
  'n_test_null': 0},
 'loggamma': {'chi_square': {'test_statistic': np.float64(14.701357421346438),
   'critical_value': np.float64(22.362032494826934),
   'p_value': np.float64(0.326365524186357),
   'rejected': np.False_},
  'kolmogorov_smirnov': {'test_statistic': np.float64(0.011717515199630213),
   'critical_value': np.float64(0.02915677208094496),
   'p_value': np.float64(0.9249481125842145),
   'rejected': np.False_},
  'anderson_darling': {'test_statistic': np.float64(0.2119159173380467),
   'critical_value': np.float64(2.4923268305268924),
   'p_value': np.float64(0.9868080417003893),
   'rejected': np.False_},
  'aic': 19823.770294642767,
  'bic': np.float64(19840.80110608022),
  'sse': np.float64(2.002565446911337e-06),
  'parameters': {'c': np.float64(7.7906855219975215),
   'mu': np.float64(753.8625547143147),
   'sigma': np.float64(65.25437287614032)},
  'n_test_passed': 3,
  'n_test_null': 0},
 'weibull_3p': {'chi_square': {'test_statistic': np.float64(19.50613582857832),
   'critical_value': np.float64(22.362032494826934),
   'p_value': np.float64(0.10822732913122812),
   'rejected': np.False_},
  'kolmogorov_smirnov': {'test_statistic': np.float64(0.009407842957641632),
   'critical_value': np.float64(0.02915677208094496),
   'p_value': np.float64(0.9901254125553746),
   'rejected': np.False_},
  'anderson_darling': {'test_statistic': np.float64(0.29860389985151414),
   'critical_value': np.float64(2.4923268305268924),
   'p_value': np.float64(0.9391981995286119),
   'rejected': np.False_},
  'aic': 19827.109093331717,
  'bic': np.float64(19844.13990476917),
  'sse': np.float64(2.1120082501326804e-06),
  'parameters': {'alpha': np.float64(5.963385914534697),
   'loc': np.float64(759.6272393966783),
   'beta': np.float64(133.62071167922645)},
  'n_test_passed': 3,
  'n_test_null': 0},
 'johnson_sb': {'chi_square': {'test_statistic': np.float64(15.51243131262429),
   'critical_value': np.float64(21.02606981748307),
   'p_value': np.float64(0.21460140992906707),
   'rejected': np.False_},
  'kolmogorov_smirnov': {'test_statistic': np.float64(0.011890836993289633),
   'critical_value': np.float64(0.02915677208094496),
   'p_value': np.float64(0.9167538887417859),
   'rejected': np.False_},
  'anderson_darling': {'test_statistic': np.float64(0.23283036612247088),
   'critical_value': np.float64(2.4923268305268924),
   'p_value': np.float64(0.9787188080165576),
   'rejected': np.False_},
  'aic': 19826.106561939083,
  'bic': np.float64(19848.814310522353),
  'sse': np.float64(2.005554104701933e-06),
  'parameters': {'xi': np.float64(-161.32891731800058),
   'lambda': np.float64(1213.5774041868667),
   'gamma': np.float64(-11.039815662319977),
   'delta': np.float64(6.020654944380659)},
  'n_test_passed': 3,
  'n_test_null': 0},
 'non_central_t_student': {'chi_square': {'test_statistic': np.float64(14.892833917648082),
   'critical_value': np.float64(21.02606981748307),
   'p_value': np.float64(0.24734947217500347),
   'rejected': np.False_},
  'kolmogorov_smirnov': {'test_statistic': np.float64(0.014306695135527847),
   'critical_value': np.float64(0.02915677208094496),
   'p_value': np.float64(0.7633828176973931),
   'rejected': np.False_},
  'anderson_darling': {'test_statistic': np.float64(0.34046823096605294),
   'critical_value': np.float64(2.4923268305268924),
   'p_value': np.float64(0.9049521461453793),
   'rejected': np.False_},
  'aic': 19826.646604599417,
  'bic': np.float64(19849.354353182687),
  'sse': np.float64(2.360890044189441e-06),
  'parameters': {'lambda': np.float64(-11.12433544321511),
   'n': np.float64(70.790692022514),
   'loc': np.float64(1077.9237897863886),
   'scale': np.float64(17.287164950693427)},
  'n_test_passed': 3,
  'n_test_null': 0},
 'johnson_su': {'chi_square': {'test_statistic': np.float64(20.14814198059029),
   'critical_value': np.float64(21.02606981748307),
   'p_value': np.float64(0.06433499733719239),
   'rejected': np.False_},
  'kolmogorov_smirnov': {'test_statistic': np.float64(0.011702194231956842),
   'critical_value': np.float64(0.02915677208094496),
   'p_value': np.float64(0.9256503884727609),
   'rejected': np.False_},
  'anderson_darling': {'test_statistic': np.float64(0.30464867946557206),
   'critical_value': np.float64(2.4923268305268924),
   'p_value': np.float64(0.934620463180324),
   'rejected': np.False_},
  'aic': 19829.8068796379,
  'bic': np.float64(19852.51462822117),
  'sse': np.float64(2.1552270776039404e-06),
  'parameters': {'xi': np.float64(1028.6008917406054),
   'lambda': np.float64(39.19044903123062),
   'gamma': np.float64(12.564545656178632),
   'delta': np.float64(6.261301589405481)},
  'n_test_passed': 3,
  'n_test_null': 0},
 'burr': {'chi_square': {'test_statistic': np.float64(21.655527624854372),
   'critical_value': np.float64(22.362032494826934),
   'p_value': np.float64(0.060934396276894676),
   'rejected': np.False_},
  'kolmogorov_smirnov': {'test_statistic': np.float64(0.025207047648464487),
   'critical_value': np.float64(0.02915677208094496),
   'p_value': np.float64(0.12664292490139972),
   'rejected': np.False_},
  'anderson_darling': {'test_statistic': np.float64(1.8574825839828009),
   'critical_value': np.float64(2.4923268305268924),
   'p_value': np.float64(0.11017027175229788),
   'rejected': np.False_},
  'aic': 19840.645428743832,
  'bic': np.float64(19857.676240181285),
  'sse': np.float64(5.4389524257548525e-06),
  'parameters': {'A': np.float64(904.4523694683762),
   'B': np.float64(51.636740559663416),
   'C': np.float64(2.5063959520766357)},
  'n_test_passed': 3,
  'n_test_null': 0},
 'burr_4p': {'chi_square': {'test_statistic': np.float64(19.37192340136254),
   'critical_value': np.float64(21.02606981748307),
   'p_value': np.float64(0.079939481370359),
   'rejected': np.False_},
  'kolmogorov_smirnov': {'test_statistic': np.float64(0.018165762511881733),
   'critical_value': np.float64(0.02915677208094496),
   'p_value': np.float64(0.4692154128940059),
   'rejected': np.False_},
  'anderson_darling': {'test_statistic': np.float64(0.7126759486468472),
   'critical_value': np.float64(2.4923268305268924),
   'p_value': np.float64(0.5483203376842196),
   'rejected': np.False_},
  'aic': 19839.767214987238,
  'bic': np.float64(19862.47496357051),
  'sse': np.float64(4.978267402573367e-06),
  'parameters': {'A': np.float64(904.4523694683762),
   'B': np.float64(51.636740559663416),
   'C': np.float64(2.5063959520766357),
   'loc': np.float64(0.8460973115800341)},
  'n_test_passed': 3,
  'n_test_null': 0},
 'kumaraswamy': {'chi_square': {'test_statistic': np.float64(28.256278368815405),
   'critical_value': np.float64(21.02606981748307),
   'p_value': np.float64(0.005073671640993926),
   'rejected': np.True_},
  'kolmogorov_smirnov': {'test_statistic': np.float64(0.012157668413438794),
   'critical_value': np.float64(0.02915677208094496),
   'p_value': np.float64(0.9032618136671798),
   'rejected': np.False_},
  'anderson_darling': {'test_statistic': np.float64(0.49870451468677857),
   'critical_value': np.float64(2.4923268305268924),
   'p_value': np.float64(0.7481211606488822),
   'rejected': np.False_},
  'aic': 19834.733154911184,
  'bic': np.float64(19857.440903494455),
  'sse': np.float64(2.747328700286749e-06),
  'parameters': {'alpha': np.float64(6.80107701346655),
   'beta': np.float64(137.97784453905385),
   'min': np.float64(743.2415228907947),
   'max': np.float64(1053.419104283398)},
  'n_test_passed': 2,
  'n_test_null': 0},
 'beta': {'chi_square': {'test_statistic': np.float64(27.57659041908278),
   'critical_value': np.float64(21.02606981748307),
   'p_value': np.float64(0.006377072851541987),
   'rejected': np.True_},
  'kolmogorov_smirnov': {'test_statistic': np.float64(0.010233296920341028),
   'critical_value': np.float64(0.02915677208094496),
   'p_value': np.float64(0.9758613934440539),
   'rejected': np.False_},
  'anderson_darling': {'test_statistic': np.float64(0.36426366739488003),
   'critical_value': np.float64(2.4923268305268924),
   'p_value': np.float64(0.8832847743621575),
   'rejected': np.False_},
  'aic': 19835.98927824226,
  'bic': np.float64(19858.69702682553),
  'sse': np.float64(2.2981606559500745e-06),
  'parameters': {'alpha': np.float64(45.83246778284843),
   'beta': np.float64(10.337834518530881),
   'A': np.float64(499.0939442805805),
   'B': np.float64(970.2639535360801)},
  'n_test_passed': 2,
  'n_test_null': 0},
 'dagum_4p': {'chi_square': {'test_statistic': np.float64(34.2029760606009),
   'critical_value': np.float64(21.02606981748307),
   'p_value': np.float64(0.0006265685281567901),
   'rejected': np.True_},
  'kolmogorov_smirnov': {'test_statistic': np.float64(0.024180808390558917),
   'critical_value': np.float64(0.02915677208094496),
   'p_value': np.float64(0.15768632314869158),
   'rejected': np.False_},
  'anderson_darling': {'test_statistic': np.float64(2.226239638698189),
   'critical_value': np.float64(2.4923268305268924),
   'p_value': np.float64(0.06921896193386101),
   'rejected': np.False_},
  'aic': 19850.32758478143,
  'bic': np.float64(19873.0353333647),
  'sse': np.float64(1.1557906414817067e-05),
  'parameters': {'a': np.float64(73.80896034958256),
   'b': np.float64(896.2435914160488),
   'p': np.float64(0.7126797543833516),
   'loc': np.float64(-5.087454845730419)},
  'n_test_passed': 2,
  'n_test_null': 0},
 'mcdonald': {'chi_square': {'test_statistic': np.float64(44.59112265547088),
   'critical_value': np.float64(19.67513757268249),
   'p_value': np.float64(5.724890346447964e-06),
   'rejected': np.True_},
  'kolmogorov_smirnov': {'test_statistic': np.float64(0.013048660166198767),
   'critical_value': np.float64(0.02915677208094496),
   'p_value': np.float64(0.8511755883483547),
   'rejected': np.False_},
  'anderson_darling': {'test_statistic': np.float64(0.6033258966044741),
   'critical_value': np.float64(2.4923268305268924),
   'p_value': np.float64(0.6448424071872134),
   'rejected': np.False_},
  'aic': 19849.643585592297,
  'bic': np.float64(19878.02827132139),
  'sse': np.float64(2.8617908785543238e-06),
  'parameters': {'a': np.float64(3.9328335016183975),
   'b': np.float64(9.02159903283252),
   'c': np.float64(4.476005632248741),
   'min': np.float64(638.2258901219277),
   'max': np.float64(963.5271823770134)},
  'n_test_passed': 2,
  'n_test_null': 0},
 'exponentiated_kumaraswamy': {'chi_square': {'test_statistic': np.float64(56.825252808944406),
   'critical_value': np.float64(19.67513757268249),
   'p_value': np.float64(3.583181940047808e-08),
   'rejected': np.True_},
  'kolmogorov_smirnov': {'test_statistic': np.float64(0.012750515738244372),
   'critical_value': np.float64(0.02915677208094496),
   'p_value': np.float64(0.8697237674954928),
   'rejected': np.False_},
  'anderson_darling': {'test_statistic': np.float64(0.6388918841721534),
   'critical_value': np.float64(2.4923268305268924),
   'p_value': np.float64(0.6119914974165406),
   'rejected': np.False_},
  'aic': 19861.328562231913,
  'bic': np.float64(19889.713247961005),
  'sse': np.float64(2.8837077797743062e-06),
  'parameters': {'alpha': np.float64(6.515706133219352),
   'beta': np.float64(6.168209535380089),
   'lambda': np.float64(2.775199991203011),
   'min': np.float64(619.6455405936982),
   'max': np.float64(955.7862694254383)},
  'n_test_passed': 2,
  'n_test_null': 0},
 'half_normal': {'chi_square': {'test_statistic': np.float64(1967.1726596816286),
   'critical_value': np.float64(23.684791304840576),
   'p_value': np.float64(0.0),
   'rejected': np.True_},
  'kolmogorov_smirnov': {'test_statistic': np.float64(0.9173802353596332),
   'critical_value': np.float64(0.02915677208094496),
   'p_value': np.float64(0.0),
   'rejected': np.True_},
  'anderson_darling': {'test_statistic': None,
   'critical_value': None,
   'p_value': None,
   'rejected': None},
  'aic': 19063.778808730003,
  'bic': np.float64(19075.13268302164),
  'sse': np.float64(0.0013146655976853927),
  'parameters': {'mu': np.float64(851.5848052687289),
   'sigma': np.float64(40.0595715351334)},
  'n_test_passed': 0,
  'n_test_null': 1},
 'normal': {'chi_square': {'test_statistic': np.float64(60.51643239531984),
   'critical_value': np.float64(23.684791304840576),
   'p_value': np.float64(9.521756016983574e-08),
   'rejected': np.True_},
  'kolmogorov_smirnov': {'test_statistic': np.float64(0.035447930380450965),
   'critical_value': np.float64(0.02915677208094496),
   'p_value': np.float64(0.008610748147569125),
   'rejected': np.True_},
  'anderson_darling': {'test_statistic': np.float64(4.022972110796218),
   'critical_value': np.float64(2.4923268305268924),
   'p_value': np.float64(0.008498410517288058),
   'rejected': np.True_},
  'aic': 19870.210078147247,
  'bic': np.float64(19881.563952438883),
  'sse': np.float64(1.179790645625211e-05),
  'parameters': {'mu': np.float64(883.5477189089899),
   'sigma': np.float64(24.148321333038766)},
  'n_test_passed': 0,
  'n_test_null': 0},
 'rice': {'chi_square': {'test_statistic': np.float64(60.522961764125974),
   'critical_value': np.float64(23.684791304840576),
   'p_value': np.float64(9.496635755557037e-08),
   'rejected': np.True_},
  'kolmogorov_smirnov': {'test_statistic': np.float64(0.03544926247016156),
   'critical_value': np.float64(0.02915677208094496),
   'p_value': np.float64(0.008607229791688598),
   'rejected': np.True_},
  'anderson_darling': {'test_statistic': np.float64(4.023356725327176),
   'critical_value': np.float64(2.4923268305268924),
   'p_value': np.float64(0.00849473573170867),
   'rejected': np.True_},
  'aic': 19870.215579761832,
  'bic': np.float64(19881.569454053468),
  'sse': np.float64(1.1798885870835775e-05),
  'parameters': {'v': np.float64(883.2174101471106),
   'sigma': np.float64(24.152840676758686)},
  'n_test_passed': 0,
  'n_test_null': 0},
 'generalized_normal': {'chi_square': {'test_statistic': np.float64(52.96347396721571),
   'critical_value': np.float64(22.362032494826934),
   'p_value': np.float64(9.169967402078427e-07),
   'rejected': np.True_},
  'kolmogorov_smirnov': {'test_statistic': np.float64(0.03146924097376058),
   'critical_value': np.float64(0.02915677208094496),
   'p_value': np.float64(0.02725461616236413),
   'rejected': np.True_},
  'anderson_darling': {'test_statistic': np.float64(3.566837037175901),
   'critical_value': np.float64(2.4923268305268924),
   'p_value': np.float64(0.014239764345318817),
   'rejected': np.True_},
  'aic': 19870.46553351934,
  'bic': np.float64(19887.49634495679),
  'sse': np.float64(1.164342999047156e-05),
  'parameters': {'beta': np.float64(1.879226190935344),
   'mu': np.float64(883.7454919029467),
   'alpha': np.float64(32.99544726386294)},
  'n_test_passed': 0,
  'n_test_null': 0},
 't_student_3p': {'chi_square': {'test_statistic': np.float64(60.59535381689419),
   'critical_value': np.float64(22.362032494826934),
   'p_value': np.float64(4.110334961282547e-08),
   'rejected': np.True_},
  'kolmogorov_smirnov': {'test_statistic': np.float64(0.03543421160444482),
   'critical_value': np.float64(0.02915677208094496),
   'p_value': np.float64(0.008647058659201567),
   'rejected': np.True_},
  'anderson_darling': {'test_statistic': np.float64(4.021428407899748),
   'critical_value': np.float64(2.4923268305268924),
   'p_value': np.float64(0.008513176127999844),
   'rejected': np.True_},
  'aic': 19872.208808284162,
  'bic': np.float64(19889.239619721615),
  'sse': np.float64(1.1794798712464517e-05),
  'parameters': {'df': np.float64(214406.25776772574),
   'loc': np.float64(883.5477526862255),
   'scale': np.float64(24.142609142084765)},
  'n_test_passed': 0,
  'n_test_null': 0},
 'dagum': {'chi_square': {'test_statistic': np.float64(48.989477164836025),
   'critical_value': np.float64(22.362032494826934),
   'p_value': np.float64(4.439644491260886e-06),
   'rejected': np.True_},
  'kolmogorov_smirnov': {'test_statistic': np.float64(0.03447963378211649),
   'critical_value': np.float64(0.02915677208094496),
   'p_value': np.float64(0.011542376930023024),
   'rejected': np.True_},
  'anderson_darling': {'test_statistic': np.float64(4.600068305715467),
   'critical_value': np.float64(2.4923268305268924),
   'p_value': np.float64(0.004460416983611215),
   'rejected': np.True_},
  'aic': 19875.55329320224,
  'bic': np.float64(19892.584104639693),
  'sse': np.float64(2.2066428529362482e-05),
  'parameters': {'a': np.float64(88.11625149154641),
   'b': np.float64(895.1315409000871),
   'p': np.float64(0.5447255036123255)},
  'n_test_passed': 0,
  'n_test_null': 0},
 'generalized_logistic': {'chi_square': {'test_statistic': np.float64(50.75142764506321),
   'critical_value': np.float64(22.362032494826934),
   'p_value': np.float64(2.2144979012761468e-06),
   'rejected': np.True_},
  'kolmogorov_smirnov': {'test_statistic': np.float64(0.035414812241991445),
   'critical_value': np.float64(0.02915677208094496),
   'p_value': np.float64(0.008698641743906443),
   'rejected': np.True_},
  'anderson_darling': {'test_statistic': np.float64(4.851763241342269),
   'critical_value': np.float64(2.4923268305268924),
   'p_value': np.float64(0.003375754808245257),
   'rejected': np.True_},
  'aic': 19877.639315901426,
  'bic': np.float64(19894.67012733888),
  'sse': np.float64(2.2733040688188537e-05),
  'parameters': {'c': np.float64(0.5926516281300741),
   'loc': np.float64(893.8822785170362),
   'scale': np.float64(10.43471621373777)},
  'n_test_passed': 0,
  'n_test_null': 0},
 'gamma': {'chi_square': {'test_statistic': np.float64(80.83404072476705),
   'critical_value': np.float64(23.684791304840576),
   'p_value': np.float64(1.9810486584503906e-11),
   'rejected': np.True_},
  'kolmogorov_smirnov': {'test_statistic': np.float64(0.03897727834543263),
   'critical_value': np.float64(0.02915677208094496),
   'p_value': np.float64(0.0027631680283340954),
   'rejected': np.True_},
  'anderson_darling': {'test_statistic': np.float64(5.116282956599207),
   'critical_value': np.float64(2.4923268305268924),
   'p_value': np.float64(0.0025229461691406163),
   'rejected': np.True_},
  'aic': 19886.01451551461,
  'bic': np.float64(19897.368389806245),
  'sse': np.float64(1.4580538858282085e-05),
  'parameters': {'alpha': np.float64(1338.7088286413687),
   'beta': np.float64(0.6599999193294979)},
  'n_test_passed': 0,
  'n_test_null': 0},
 'erlang': {'chi_square': {'test_statistic': np.float64(81.7731973617431),
   'critical_value': np.float64(23.684791304840576),
   'p_value': np.float64(1.3250844865808631e-11),
   'rejected': np.True_},
  'kolmogorov_smirnov': {'test_statistic': np.float64(0.03582975292896251),
   'critical_value': np.float64(0.02915677208094496),
   'p_value': np.float64(0.007654091524526452),
   'rejected': np.True_},
  'anderson_darling': {'test_statistic': np.float64(4.651510887093536),
   'critical_value': np.float64(2.4923268305268924),
   'p_value': np.float64(0.004212995778911877),
   'rejected': np.True_},
  'aic': 19886.1546796811,
  'bic': np.float64(19897.508553972737),
  'sse': np.float64(1.3621357260361676e-05),

In [13]:
phi.get_test_chi_square("beta")

{'test_statistic': np.float64(27.57659041908278),
 'critical_value': np.float64(21.02606981748307),
 'p_value': np.float64(0.006377072851541987),
 'rejected': np.True_}